// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class CadastrarFundamentacaoJuridicaTest {
  
  CadastrarFundamentacaoJuridicaPageObject fundamentacaoJuridicaPageObject;
  private IWebDriver driver;

  [SetUp]
  public void SetUp() {
    string path = "C:\\Users\\Usuário\\Desktop\\SIAIAP Concessoes Testes Automatizados\\driver";
    driver = new ChromeDriver(ChromeDriverService.CreateDefaultService(path));
    fundamentacaoJuridicaPageObject = new CadastrarFundamentacaoJuridicaPageObject(driver);
  }

  [TearDown]
  protected void TearDown()
  {
    fundamentacaoJuridicaPageObject.Quit(driver);
  }

  [Test, Order(1)]
  public void cadastrarFundamentacaoJuridica() {
    FundamentacaoJuridica fundamentacaoJuridica = new FundamentacaoJuridica();
    fundamentacaoJuridica.idTipoAto = "Civil - Aposentadoria Especial";
    fundamentacaoJuridica.idOrgao = "TRIBUNAL DE CONTAS DO ESTADO";
    fundamentacaoJuridica.dataInicioVigencia = "13/05/2020";
    fundamentacaoJuridica.dataFimVigencia = "22/05/2020";
    fundamentacaoJuridica.descricaoFundamentacaoJuridicaConcessao = "TESTE DESCRICAO";
    fundamentacaoJuridica.ementa = "TESTE EMENTA";

    fundamentacaoJuridicaPageObject.PreencherForm(fundamentacaoJuridica);
    fundamentacaoJuridicaPageObject.BuscarElementoPeloId("tce-buttons-submit-0").Click();
    fundamentacaoJuridicaPageObject.WaitSeconds(5);
    fundamentacaoJuridicaPageObject.Wait().Until(e => fundamentacaoJuridicaPageObject.BuscarElementoPeloCss(".swal-title"));
    fundamentacaoJuridicaPageObject.BuscarElementoPeloXPath("//body/div/div/div[2][contains(.,'Sucesso')]");
  }

  [Test, Order(2)]
  public void cadastrarComDataFinalVigenciaVazio() {
    FundamentacaoJuridica fundamentacaoJuridica = new FundamentacaoJuridica();
    fundamentacaoJuridica.idTipoAto = "Civil - Aposentadoria Especial";
    fundamentacaoJuridica.idOrgao = "TRIBUNAL DE CONTAS DO ESTADO";
    fundamentacaoJuridica.dataInicioVigencia = "13/05/2020";
    fundamentacaoJuridica.descricaoFundamentacaoJuridicaConcessao = "TESTE DESCRICAO";
    fundamentacaoJuridica.ementa = "TESTE EMENTA";

    fundamentacaoJuridicaPageObject.PreencherForm(fundamentacaoJuridica);
    fundamentacaoJuridicaPageObject.BuscarElementoPeloId("tce-buttons-submit-0").Click();
    fundamentacaoJuridicaPageObject.WaitSeconds(5);
    fundamentacaoJuridicaPageObject.Wait().Until(e => fundamentacaoJuridicaPageObject.BuscarElementoPeloCss(".swal-title"));
    fundamentacaoJuridicaPageObject.BuscarElementoPeloXPath("//body/div/div/div[2][contains(.,'Sucesso')]");
  }

  [Test, Order(3)]
  public void cadastrarDataFinalIgualDataInicio() {
    FundamentacaoJuridica fundamentacaoJuridica = new FundamentacaoJuridica();
    fundamentacaoJuridica.idTipoAto = "Civil - Aposentadoria Especial";
    fundamentacaoJuridica.idOrgao = "TRIBUNAL DE CONTAS DO ESTADO";
    fundamentacaoJuridica.dataInicioVigencia = "13/05/2020";
    fundamentacaoJuridica.dataFimVigencia = "13/05/2020";
    fundamentacaoJuridica.descricaoFundamentacaoJuridicaConcessao = "TESTE DESCRICAO";
    fundamentacaoJuridica.ementa = "TESTE EMENTA";

    fundamentacaoJuridicaPageObject.PreencherForm(fundamentacaoJuridica);
    fundamentacaoJuridicaPageObject.BuscarElementoPeloId("tce-buttons-submit-0").Click();
    fundamentacaoJuridicaPageObject.WaitSeconds(5);
    fundamentacaoJuridicaPageObject.Wait().Until(e => fundamentacaoJuridicaPageObject.BuscarElementoPeloCss(".swal-title"));
    fundamentacaoJuridicaPageObject.BuscarElementoPeloXPath("//body/div/div/div[2][contains(.,'Sucesso')]");
  }

  [Test, Order(4)]
  public void cadastrarDataFinalMenorDataInicio() {
    FundamentacaoJuridica fundamentacaoJuridica = new FundamentacaoJuridica();
    fundamentacaoJuridica.idTipoAto = "Civil - Aposentadoria Especial";
    fundamentacaoJuridica.idOrgao = "TRIBUNAL DE CONTAS DO ESTADO";
    fundamentacaoJuridica.dataInicioVigencia = "02/05/2020";
    fundamentacaoJuridica.dataFimVigencia = "01/05/2020";
    fundamentacaoJuridica.descricaoFundamentacaoJuridicaConcessao = "TESTE DESCRICAO";
    fundamentacaoJuridica.ementa = "TESTE EMENTA";

    fundamentacaoJuridicaPageObject.PreencherForm(fundamentacaoJuridica);
    fundamentacaoJuridicaPageObject.BuscarElementoPeloId("dataFinal");
  }

  [Test, Order(5)]
  public void cadastrarCamposRequiredVazios() {
    Assert.AreEqual(fundamentacaoJuridicaPageObject.BuscarElementoPeloId("tce-buttons-submit-0").GetProperty("disabled"), "True");
  }

  [Test, Order(6)]
  public void cadastrarTipoAtoVazio() {
    FundamentacaoJuridica fundamentacaoJuridica = new FundamentacaoJuridica();
    fundamentacaoJuridica.idOrgao = "TRIBUNAL DE CONTAS DO ESTADO";
    fundamentacaoJuridica.dataInicioVigencia = "13/05/2020";
    fundamentacaoJuridica.dataFimVigencia = "22/05/2020";
    fundamentacaoJuridica.descricaoFundamentacaoJuridicaConcessao = "TESTE DESCRICAO";
    fundamentacaoJuridica.ementa = "TESTE EMENTA";

    fundamentacaoJuridicaPageObject.PreencherForm(fundamentacaoJuridica);
    Assert.AreEqual(fundamentacaoJuridicaPageObject.BuscarElementoPeloId("tce-buttons-submit-0").GetProperty("disabled"), "True");
  }

  [Test, Order(7)]
  public void cadastrarDescricaoVazia() {
    FundamentacaoJuridica fundamentacaoJuridica = new FundamentacaoJuridica();
    fundamentacaoJuridica.idTipoAto = "Civil - Aposentadoria Especial";
    fundamentacaoJuridica.idOrgao = "TRIBUNAL DE CONTAS DO ESTADO";
    fundamentacaoJuridica.dataInicioVigencia = "13/05/2020";
    fundamentacaoJuridica.dataFimVigencia = "22/05/2020";
    fundamentacaoJuridica.ementa = "TESTE EMENTA";

    fundamentacaoJuridicaPageObject.PreencherForm(fundamentacaoJuridica);
    Assert.AreEqual(fundamentacaoJuridicaPageObject.BuscarElementoPeloId("tce-buttons-submit-0").GetProperty("disabled"), "True");
  }

  [Test, Order(8)]
  public void cadastrarEmentaVazia() {
    FundamentacaoJuridica fundamentacaoJuridica = new FundamentacaoJuridica();
    fundamentacaoJuridica.idTipoAto = "Civil - Aposentadoria Especial";
    fundamentacaoJuridica.idOrgao = "TRIBUNAL DE CONTAS DO ESTADO";
    fundamentacaoJuridica.dataInicioVigencia = "13/05/2020";
    fundamentacaoJuridica.dataFimVigencia = "22/05/2020";
    fundamentacaoJuridica.descricaoFundamentacaoJuridicaConcessao = "TESTE DESCRICAO";

    fundamentacaoJuridicaPageObject.PreencherForm(fundamentacaoJuridica);
    Assert.AreEqual(fundamentacaoJuridicaPageObject.BuscarElementoPeloId("tce-buttons-submit-0").GetProperty("disabled"), "True");
  }
  
  [Test, Order(9)]
  public void cadastrarOrgaoVazio() {
    FundamentacaoJuridica fundamentacaoJuridica = new FundamentacaoJuridica();
    fundamentacaoJuridica.idTipoAto = "Civil - Aposentadoria Especial";
    fundamentacaoJuridica.dataInicioVigencia = "13/05/2020";
    fundamentacaoJuridica.dataFimVigencia = "22/05/2020";
    fundamentacaoJuridica.descricaoFundamentacaoJuridicaConcessao = "TESTE DESCRICAO";
    fundamentacaoJuridica.ementa = "TESTE EMENTA";

    fundamentacaoJuridicaPageObject.PreencherForm(fundamentacaoJuridica);
    Assert.AreEqual(fundamentacaoJuridicaPageObject.BuscarElementoPeloId("tce-buttons-submit-0").GetProperty("disabled"), "True");
  }
}
