// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class CadastrarFundamentacaoJuridicaPageObject {
  
  private IWebDriver driver;
  private WebDriverWait wait;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;

  public IWebElement BuscarElementoPeloId(string id)
  {
      return driver.FindElement(By.Id(id));
  }

  public IWebElement BuscarElementoPeloXPath(string xpath)
  {
      return driver.FindElement(By.XPath(xpath));
  }

  public IWebElement BuscarElementoPeloCss(string css)
  {
      return driver.FindElement(By.CssSelector(css));
  }

  public WebDriverWait Wait()
  {
    return wait;
  }

  public void WaitSeconds(int seconds){
    Thread.Sleep(seconds*1000);
  }

  private void LimparMemoria() 
  {
    string comando = "/C taskkill /F /IM chromedriver.exe /T";
    System.Diagnostics.Process.Start("CMD.exe", comando);
  }

  public CadastrarFundamentacaoJuridicaPageObject(IWebDriver IWebDriver)
  {
      driver = IWebDriver;
      driver.Manage().Window.Maximize();
      driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(10);

      js = (IJavaScriptExecutor)driver;

      wait = new WebDriverWait(driver, new TimeSpan(0, 5, 0));

      LogarNoSistema();
  }

  public void Quit(IWebDriver IWebDriver)
  {
      driver.Quit();
      driver.Dispose();
      LimparMemoria();
  }

  public void LogarNoSistema()
  {
    driver.Navigate().GoToUrl("http://localhost:4200");
    BuscarElementoPeloId("username").Click();
    BuscarElementoPeloId("username").SendKeys("05510151447");
    BuscarElementoPeloId("password").SendKeys("tce@123");
    BuscarElementoPeloCss(".ng-input > input").Click();
    wait.Until(e => BuscarElementoPeloXPath("/html/body/ng-dropdown-panel/div/div[2]/div[2]/span")).Click();
    BuscarElementoPeloCss(".btn-login").Click();

    wait.Until(e => BuscarElementoPeloXPath("/html/body/app-root/app-dashboard/div[1]/tce-menu-side/div/aside/tce-menu-modulos-paginas/ul[1]/li[2]/a"));
    {
      WaitSeconds(8);
      BuscarElementoPeloXPath("/html/body/app-root/app-dashboard/div[1]/tce-menu-side/div/aside/tce-menu-modulos-paginas/ul[1]/li[2]/a").Click();
      BuscarElementoPeloId("FundamentacaoJuridica").Click();
      WaitSeconds(5);
      BuscarElementoPeloId("fundamentacao_juridica-novo").Click();
      WaitSeconds(5);
    }
  }

  public void PreencherForm(FundamentacaoJuridica fundamentacaoJuridica){
    if(fundamentacaoJuridica.idTipoAto != ""){
      BuscarElementoPeloId("idTipoAto").Click();
      BuscarElementoPeloXPath("//span[contains(.,'" + fundamentacaoJuridica.idTipoAto + "')]").Click();
      BuscarElementoPeloId("acao").Click();
    }
    if(fundamentacaoJuridica.idOrgao != ""){
      BuscarElementoPeloId("idOrgao").Click();
      BuscarElementoPeloXPath("//span[contains(.,'" + fundamentacaoJuridica.idOrgao + "')]").Click();
      BuscarElementoPeloXPath("(//button[@type='button'])[4]").Click();
    }
    if(fundamentacaoJuridica.dataInicioVigencia != ""){
      BuscarElementoPeloId("dataInicioVigencia").Click();
      BuscarElementoPeloId("dataInicioVigencia").SendKeys(fundamentacaoJuridica.dataInicioVigencia);
    }
    if(fundamentacaoJuridica.dataFimVigencia != ""){
      BuscarElementoPeloId("dataFimVigencia").Click();
      BuscarElementoPeloId("dataFimVigencia").SendKeys(fundamentacaoJuridica.dataFimVigencia);
    }
    if(fundamentacaoJuridica.descricaoFundamentacaoJuridicaConcessao != ""){
      BuscarElementoPeloId("descricaoFundamentacaoJuridicaConcessao").Click();
      BuscarElementoPeloId("descricaoFundamentacaoJuridicaConcessao").SendKeys(fundamentacaoJuridica.descricaoFundamentacaoJuridicaConcessao);
    }
    if(fundamentacaoJuridica.ementa != ""){
      BuscarElementoPeloId("ementa").Click();
      BuscarElementoPeloId("ementa").SendKeys(fundamentacaoJuridica.ementa);
    }
  }

  [TearDown]
  protected void TearDown() {
    LimparMemoria();
    driver.Quit();
  }

}

public class FundamentacaoJuridica {
  public string idTipoAto = "";
  public string idOrgao = "";
  public string dataInicioVigencia = "";
  public string dataFimVigencia = "";
  public string descricaoFundamentacaoJuridicaConcessao = "";
  public string ementa = "";
}